### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Nice work on this app!
Here is a French translation.

### CODE REVIEW

**Comment by cibersheep** [comment]
Thank you for your collaboration, we will add your translation to the next release <3

**Comment by cibersheep** [comment]
@Anne017 I have updated the pot file, so there's new strings to translate if you have time:
https://github.com/Jujuyeh/webapp-creator/blob/master/webapp-creator/po/webapp-creator.jujuyeh.pot

**Comment by ghost** [comment]
I double checked, but the latest commits seem to not have introduced new strings to translate, so everything is alright for me!

**Comment by cibersheep** [comment]
Then I didn't upload the correct pot.
Let me check it and solve it. Sorry

**Comment by cibersheep** [comment]
@Anne017 pot updated. Sorry about that
https://github.com/Jujuyeh/webapp-creator/blob/master/webapp-creator/po/webapp-creator.jujuyeh.pot

If you use https://poedit.net/ you might need to do: Catalog/update from POT...

**Comment by ghost** [comment]
@cibersheep no problem, a new pull request is available.
Thank you again for this hard work, this is an unvaluable contribution to the whole ecosystem.

**Pull request merged**
